workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      node: 22
      java: 17
    scripts:
      - name: Install npm dependencies
        script: npm ci
      - name: Build web assets
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync android
      - name: Build Android debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk

  ios-debug:
    name: iOS Debug Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      node: 22
      xcode: latest
    scripts:
      - name: Install npm dependencies
        script: npm ci
      - name: Build web assets
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Build iOS debug app
        script: |
          cd ios/App
          xcodebuild build \
            -project App.xcodeproj \
            -scheme App \
            -configuration Debug \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ios/App/build/**/*.app
